FROM python:3

ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
COPY . /code/

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev


RUN pip install flake8
COPY . .
RUN flake8 --ignore=E501,F401 .

RUN pip install -r requirement.txt
EXPOSE 8989
#ENTRYPOINT python manage.py runserver 0.0.0.0:8989