version: '3'
services:
  web:
    build: .
    image: srikanthamudala/sample-django-project
    command: gunicorn djangoProjectV1.wsgi:application --bind 0.0.0.0:8000

    volumes:
        - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
  
  nginx:
    build: ./nginx
    depends_on: 
      - web
    command: nginx -g 'daemon off;'
    ports: 
      - "80:80"
    volumes: 
      - ./static:/var/www/static
      - ./media:/var/www/media
